apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: resilience-ai-kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  deployment:
    accessible_namespaces:
    - "**"
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 500m
  server:
    web_root: /kiali
  external_services:
    prometheus:
      url: http://prometheus.monitoring.svc.cluster.local:9090
    grafana:
      enabled: true
      in_cluster_url: http://grafana.monitoring.svc.cluster.local:3000
      url: https://grafana.resilience-ai.example.com
    tracing:
      enabled: true
      in_cluster_url: http://jaeger-query.observability.svc.cluster.local:16686
      url: https://jaeger.resilience-ai.example.com
  kiali_feature_flags:
    validations:
      ignore: ["KIA1201"]
